//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartTable
    {
        public int cartId { get; set; }
        public int fkProductId { get; set; }
        public string productName { get; set; }
        public int fkUserId { get; set; }
        public double price { get; set; }
        public int status { get; set; }
    
        public virtual ProductTable ProductTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
