//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetailsTable
    {
        public int orderDetailId { get; set; }
        public int fkOrderId { get; set; }
        public int fkUserId { get; set; }
        public string productName { get; set; }
        public int pricePerProduct { get; set; }
        public int totalOrderPrice { get; set; }
        public System.DateTime dateOfOrder { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
