//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTable()
        {
            this.CartTables = new HashSet<CartTable>();
        }
    
        public int productId { get; set; }
        public string productName { get; set; }
        public string productImagePath { get; set; }
        public double price { get; set; }
        public string description { get; set; }
        public int status { get; set; }
        public int fkCategoryId { get; set; }
        public int fkUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartTable> CartTables { get; set; }
        public virtual CategoryTable CategoryTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
